### ISSUE TITLE
Platform error sensor.viva - Integration 'viva' not found.

### ISSUE THREAD

**Issue by cappadanna** [patrickribbing/viva-component#1]
Hi. Have installed component using HACS and added in configuration.yaml but I only get "Platform error sensor.viva - Integration 'viva' not found"

**Comment by Tandolfss** [comment]
Hi cappadanna, 

i had the same problem. the problem is that the newest version of HA (since jan 2021) require a version number in the manifest. 

all you need to add in the manifest is "version": "v1.0.0", and it should work. ps dont forget the comma.

![image](https://user-images.githubusercontent.com/80855289/121788217-d65ab300-cbcb-11eb-865e-106fe1a2faee.png)

**Comment by cappadanna** [comment]
Thank you so much Tandolfss! That was it.
